// Δεδομένα της σελίδας αγώνων (agones / agones-en).
// Κάθε αγώνας: type = road|mountain|ultra, region = gr|eu, month = 1-12,
// lat/lng ως strings (διατηρούν τα δεκαδικά ψηφία όπως γράφτηκαν),
// url ανά γλώσσα (κάποια sites έχουν ξεχωριστό EN path).
// Το προαιρετικό note εμφανίζεται ως πορτοκαλί σημείωση στην κάρτα.

module.exports = {
  typeLabels: {
    road: { el: "Δρόμου", en: "Road" },
    mountain: { el: "Ορεινός", en: "Mountain" },
    ultra: { el: "Υπερμαραθώνιος", en: "Ultra" },
  },

  monthNames: {
    el: ["Ιανουάριος", "Φεβρουάριος", "Μάρτιος", "Απρίλιος", "Μάιος", "Ιούνιος",
         "Ιούλιος", "Αύγουστος", "Σεπτέμβριος", "Οκτώβριος", "Νοέμβριος", "Δεκέμβριος"],
    en: ["January", "February", "March", "April", "May", "June",
         "July", "August", "September", "October", "November", "December"],
  },

  list: [
    // ── Ελλάδα ──────────────────────────────────────────────────────────
    {
      id: "athens-authentic-marathon",
      type: "road", region: "gr", month: 11,
      lat: "38.155", lng: "23.965",
      name: { el: "Αυθεντικός Μαραθώνιος Αθήνας", en: "Athens Authentic Marathon" },
      specs: { el: "42,2 χλμ · Άσφαλτος", en: "42.2 km · Road" },
      desc: {
        el: "Ο ιστορικός μαραθώνιος, από τον Μαραθώνα στο Καλλιμάρμαρο — η διαδρομή που γέννησε τον θεσμό.",
        en: "The historic marathon, from Marathon to the Panathenaic Stadium — the route that started it all.",
      },
      url: { el: "https://www.athensauthenticmarathon.gr/", en: "https://www.athensauthenticmarathon.gr/" },
    },
    {
      id: "athens-half-marathon",
      type: "road", region: "gr", month: 3,
      lat: "37.9755", lng: "23.7348",
      name: { el: "Ημιμαραθώνιος Αθήνας", en: "Athens Half Marathon" },
      specs: { el: "21,1 & 5 χλμ · Άσφαλτος", en: "21.1 & 5 km · Road" },
      desc: {
        el: "Διαδρομή μέσα στο ιστορικό κέντρο της Αθήνας, δίπλα από δεκάδες μνημεία — ιδανικό πρώτο μεγάλο βήμα πριν τον μαραθώνιο.",
        en: "A route through the historic centre of Athens, past dozens of monuments — an ideal first big step before the marathon.",
      },
      url: { el: "https://www.athinahalfmarathon.gr/", en: "https://www.athinahalfmarathon.gr/en" },
    },
    {
      id: "spartathlon",
      type: "ultra", region: "gr", month: 9,
      lat: "37.075", lng: "22.43",
      name: { el: "Σπάρταθλον", en: "Spartathlon" },
      specs: { el: "246 χλμ · Υπερμαραθώνιος", en: "246 km · Ultramarathon" },
      desc: {
        el: "Θρυλικός υπερμαραθώνιος: Αθήνα → Σπάρτη, στα χνάρια του Φειδιππίδη. Ένας από τους πιο σκληρούς αγώνες στον κόσμο.",
        en: "Legendary ultramarathon: Athens → Sparta, following the footsteps of Pheidippides. One of the toughest races in the world.",
      },
      url: { el: "https://www.spartathlon.gr/", en: "https://www.spartathlon.gr/" },
    },
    {
      id: "rodopi-ultra-trail",
      type: "ultra", region: "gr", month: 10,
      lat: "41.30", lng: "24.65",
      name: { el: "Rodopi Ultra Trail (ROUT)", en: "Rodopi Ultra Trail (ROUT)" },
      specs: { el: "100 μίλια · Ορεινός υπερμαραθώνιος", en: "100 miles · Mountain ultra" },
      desc: {
        el: "Ο παλαιότερος αγώνας 100 μιλίων στην Ελλάδα, σε συνθήκες ημι-αυτονομίας μέσα στο Εθνικό Πάρκο της Οροσειράς Ροδόπης.",
        en: "The oldest 100-mile race in Greece, run in semi-autonomy conditions through the Rodopi Mountains National Park.",
      },
      url: { el: "https://new.rout.gr/", en: "https://new.rout.gr/" },
    },
    {
      id: "olympus-marathon",
      type: "mountain", region: "gr", month: 6,
      lat: "40.088", lng: "22.50",
      name: { el: "Olympus Marathon", en: "Olympus Marathon" },
      specs: { el: "44 χλμ · Ορεινός", en: "44 km · Mountain" },
      desc: {
        el: "Απαιτητικός ορεινός αγώνας στον μυθικό Όλυμπο, με τερματισμό στους Πρίονια.",
        en: "A demanding mountain race on mythical Mount Olympus, finishing at Prionia.",
      },
      url: { el: "https://olympus-marathon.com/", en: "https://olympus-marathon.com/" },
    },
    {
      id: "zagori-mountain-running",
      type: "mountain", region: "gr", month: 7,
      lat: "39.88", lng: "20.75",
      name: { el: "Zagori Mountain Running", en: "Zagori Mountain Running" },
      specs: { el: "5–80 χλμ · Ορεινός", en: "5–80 km · Mountain" },
      desc: {
        el: "Ορεινό τρέξιμο στα μαγευτικά Ζαγοροχώρια, με διαδρομές για κάθε επίπεδο.",
        en: "Trail running in the stunning Zagori villages, with routes for every level.",
      },
      url: { el: "https://www.zagorirace.gr/", en: "https://www.zagorirace.gr/en/" },
    },
    {
      id: "metsovo-ursa-trail",
      type: "mountain", region: "gr", month: 5,
      lat: "39.770", lng: "21.183",
      name: { el: "Metsovo Ursa Trail", en: "Metsovo Ursa Trail" },
      specs: { el: "4,6–100 χλμ · Ορεινός", en: "4.6–100 km · Mountain" },
      desc: {
        el: "«Στα χνάρια της αρκούδας»: ορεινό τρέξιμο γύρω από το Μέτσοβο, από κάθετο αγώνα 4,6 χλμ μέχρι υπερμαραθώνιο 100 χλμ.",
        en: "\"On the tracks of the bear\": mountain running around Metsovo, from a 4.6 km vertical race to a 100 km ultramarathon.",
      },
      url: { el: "https://www.ursatrail.gr/", en: "https://www.ursatrail.gr/" },
    },
    {
      id: "thessaloniki-marathon",
      type: "road", region: "gr", month: 4,
      lat: "40.626", lng: "22.948",
      name: { el: "Μαραθώνιος Θεσσαλονίκης «Μέγας Αλέξανδρος»", en: "Thessaloniki Marathon \"Alexander the Great\"" },
      specs: { el: "42,2 χλμ · Άσφαλτος", en: "42.2 km · Road" },
      desc: {
        el: "Μαραθώνιος στη συμπρωτεύουσα, αφιερωμένος στον Μέγα Αλέξανδρο — από την Πέλλα στην παραλία της Θεσσαλονίκης.",
        en: "A marathon in Thessaloniki, dedicated to Alexander the Great — from Pella to the city's waterfront.",
      },
      url: { el: "https://atgm.gr/", en: "https://atgm.gr/?lang=en" },
    },
    {
      id: "thessaloniki-night-half-marathon",
      type: "road", region: "gr", month: 10,
      lat: "40.6326", lng: "22.9409",
      name: { el: "Διεθνής Νυχτερινός Ημιμαραθώνιος Θεσσαλονίκης", en: "Thessaloniki International Night Half Marathon" },
      specs: { el: "21,1 / 10 / 5 χλμ · Άσφαλτος", en: "21.1 / 10 / 5 km · Road" },
      desc: {
        el: "Νυχτερινή γιορτή δρόμου με εκκίνηση από την πλατεία Αριστοτέλους — ένας από τους πιο πολυπληθείς αγώνες της χώρας.",
        en: "A night running festival starting from Aristotelous Square — one of the biggest races in the country.",
      },
      url: { el: "https://thesshalfmarathon.org/", en: "https://thesshalfmarathon.org/?lang=en" },
    },
    {
      id: "ioannina-lake-run",
      type: "road", region: "gr", month: 9,
      lat: "39.667", lng: "20.85",
      name: { el: "Γύρος Λίμνης Ιωαννίνων (Ioannina Lake Run)", en: "Ioannina Lake Run" },
      specs: { el: "30 / 10 / 5 χλμ · Άσφαλτος", en: "30 / 10 / 5 km · Road" },
      desc: {
        el: "Δημοφιλής αγώνας γύρω από τη λίμνη Παμβώτιδα, με υπέροχη θέα.",
        en: "A popular race around Lake Pamvotida, with beautiful views.",
      },
      url: { el: "https://www.ioanninalakerun.gr/", en: "https://www.ioanninalakerun.gr/en" },
    },
    {
      id: "rhodes-marathon",
      type: "road", region: "gr", month: 4,
      lat: "36.43", lng: "28.22",
      name: { el: "Διεθνής Μαραθώνιος Ρόδου", en: "Rhodes International Marathon" },
      specs: { el: "42,2 χλμ & μικρότερες · Άσφαλτος", en: "42.2 km & shorter · Road" },
      desc: {
        el: "Μαραθώνιος με φόντο τη μεσαιωνική πόλη της Ρόδου και τη θάλασσα.",
        en: "A marathon against the backdrop of Rhodes' medieval old town and the sea.",
      },
      url: { el: "https://rhodesmarathon.gr/", en: "https://rhodesmarathon.gr/en/" },
    },
    {
      id: "messinia-challenge",
      type: "road", region: "gr", month: 5,
      lat: "36.92", lng: "21.70",
      name: { el: "Messinia Challenge (πρώην Navarino Challenge)", en: "Messinia Challenge (formerly Navarino Challenge)" },
      specs: { el: "21,1 / 10 / 5 χλμ · Άσφαλτος / Παραλία", en: "21.1 / 10 / 5 km · Road / Beach" },
      desc: {
        el: "Αθλητικό event ευεξίας στη Μεσσηνία (Costa Navarino & Πύλος), με δράσεις για όλη την οικογένεια.",
        en: "A sports & wellness event in Messinia (Costa Navarino & Pylos), with activities for the whole family.",
      },
      url: { el: "https://messiniachallenge.com/", en: "https://messiniachallenge.com/" },
    },
    {
      id: "crete-marathon",
      type: "road", region: "gr", month: 4,
      lat: "35.514", lng: "24.018",
      name: { el: "Crete Marathon (Χανιά)", en: "Crete Marathon (Chania)" },
      specs: { el: "42,2 / 10 / 5 χλμ · Άσφαλτος", en: "42.2 / 10 / 5 km · Road" },
      desc: {
        el: "Μαραθώνιος στα Χανιά, με φόντο την κρητική φύση και τη θάλασσα.",
        en: "A marathon in Chania, against the backdrop of Cretan nature and the sea.",
      },
      url: { el: "https://crete-marathon.gr/", en: "https://crete-marathon.gr/en/home/" },
    },
    {
      id: "spetses-mini-marathon",
      type: "road", region: "gr", month: 10,
      lat: "37.2635", lng: "23.159",
      name: { el: "Spetses Mini Marathon", en: "Spetses Mini Marathon" },
      specs: { el: "25 / 10 / 5 χλμ · Άσφαλτος", en: "25 / 10 / 5 km · Road" },
      desc: {
        el: "Αγωνιστικό τριήμερο στις Σπέτσες: ο κλασικός γύρος του νησιού στα 25 χλμ, μικρότερες αποστάσεις και κολυμβητικοί αγώνες.",
        en: "A racing weekend on Spetses: the classic 25 km loop of the island, shorter distances and swimming races.",
      },
      url: { el: "https://spetsesmarathon.com/", en: "https://spetsesmarathon.com/en/homepage-en/" },
    },

    // ── Ευρωπαϊκοί μαραθώνιοι & ημιμαραθώνιοι ───────────────────────────
    {
      id: "rome-marathon",
      type: "road", region: "eu", month: 3,
      lat: "41.9028", lng: "12.4964",
      country: { el: "Ιταλία", en: "Italy" },
      name: { el: "Μαραθώνιος Ρώμης", en: "Rome Marathon" },
      specs: { el: "42,2 χλμ · Άσφαλτος", en: "42.2 km · Road" },
      desc: {
        el: "Διαδρομή-μουσείο: εκκίνηση και τερματισμός στο Κολοσσαίο, περνώντας από Βατικανό, Πιάτσα Ναβόνα και όλη την αιώνια πόλη.",
        en: "A museum of a course: start and finish at the Colosseum, passing the Vatican, Piazza Navona and the whole Eternal City.",
      },
      url: { el: "https://www.runromethemarathon.com/", en: "https://www.runromethemarathon.com/" },
    },
    {
      id: "lisbon-half-marathon",
      type: "road", region: "eu", month: 3,
      lat: "38.7223", lng: "-9.1393",
      country: { el: "Πορτογαλία", en: "Portugal" },
      name: { el: "Ημιμαραθώνιος Λισαβόνας", en: "Lisbon Half Marathon" },
      specs: { el: "21,1 χλμ · Άσφαλτος", en: "21.1 km · Road" },
      desc: {
        el: "Μοναδική εκκίνηση πάνω στη γέφυρα «25ης Απριλίου» με θέα τον Τάγο — από τους πιο γρήγορους ημιμαραθώνιους στον κόσμο.",
        en: "A unique start on the 25 de Abril Bridge overlooking the Tagus — one of the fastest half marathons in the world.",
      },
      url: { el: "https://www.maratonaclubedeportugal.com/", en: "https://www.maratonaclubedeportugal.com/" },
    },
    {
      id: "london-marathon",
      type: "road", region: "eu", month: 4,
      lat: "51.5074", lng: "-0.1278",
      country: { el: "Ηνωμένο Βασίλειο", en: "United Kingdom" },
      name: { el: "Μαραθώνιος Λονδίνου", en: "London Marathon" },
      specs: { el: "42,2 χλμ · Άσφαλτος · World Marathon Major", en: "42.2 km · Road · World Marathon Major" },
      desc: {
        el: "Ένας από τους έξι World Marathon Majors: Greenwich → Tower Bridge → Buckingham Palace, με ασύγκριτη ατμόσφαιρα και κλήρωση για θέση.",
        en: "One of the six World Marathon Majors: Greenwich → Tower Bridge → Buckingham Palace, with an unmatched atmosphere and a ballot for entry.",
      },
      url: { el: "https://www.londonmarathonevents.co.uk/london-marathon", en: "https://www.londonmarathonevents.co.uk/london-marathon" },
    },
    {
      id: "paris-marathon",
      type: "road", region: "eu", month: 4,
      lat: "48.8566", lng: "2.3522",
      country: { el: "Γαλλία", en: "France" },
      name: { el: "Μαραθώνιος Παρισιού", en: "Paris Marathon" },
      specs: { el: "42,2 χλμ · Άσφαλτος", en: "42.2 km · Road" },
      desc: {
        el: "Εκκίνηση στα Ηλύσια Πεδία και διαδρομή δίπλα από Λούβρο, Σηκουάνα και Πύργο του Άιφελ — από τους μεγαλύτερους μαραθώνιους της Ευρώπης.",
        en: "Start on the Champs-Élysées, running past the Louvre, the Seine and the Eiffel Tower — one of Europe's biggest marathons.",
      },
      url: { el: "https://www.schneiderelectricparismarathon.com/", en: "https://www.schneiderelectricparismarathon.com/" },
    },
    {
      id: "vienna-city-marathon",
      type: "road", region: "eu", month: 4,
      lat: "48.2082", lng: "16.3738",
      country: { el: "Αυστρία", en: "Austria" },
      name: { el: "Μαραθώνιος Βιέννης", en: "Vienna City Marathon" },
      specs: { el: "42,2 / 21,1 χλμ · Άσφαλτος", en: "42.2 / 21.1 km · Road" },
      desc: {
        el: "Ο Vienna City Marathon περνά από Σένμπρουν, Πράτερ και Ρινγκ — μαραθώνιος και ημιμαραθώνιος με μουσική σε όλη τη διαδρομή.",
        en: "Past Schönbrunn, the Prater and the Ring — marathon and half marathon with music all along the course.",
      },
      url: { el: "https://www.vienna-marathon.com/", en: "https://www.vienna-marathon.com/" },
    },
    {
      id: "prague-marathon",
      type: "road", region: "eu", month: 5,
      lat: "50.0755", lng: "14.4378",
      country: { el: "Τσεχία", en: "Czechia" },
      name: { el: "Μαραθώνιος Πράγας", en: "Prague Marathon" },
      specs: { el: "42,2 χλμ · Άσφαλτος", en: "42.2 km · Road" },
      desc: {
        el: "Εκκίνηση στην Πλατεία της Παλιάς Πόλης και πέρασμα από τη Γέφυρα του Καρόλου — μια από τις ομορφότερες διαδρομές της Ευρώπης.",
        en: "Start in the Old Town Square and a crossing of Charles Bridge — one of the most beautiful courses in Europe.",
      },
      url: { el: "https://www.runczech.com/", en: "https://www.runczech.com/" },
    },
    {
      id: "berlin-marathon",
      type: "road", region: "eu", month: 9,
      lat: "52.5200", lng: "13.4050",
      country: { el: "Γερμανία", en: "Germany" },
      name: { el: "Μαραθώνιος Βερολίνου", en: "Berlin Marathon" },
      specs: { el: "42,2 χλμ · Άσφαλτος · World Marathon Major", en: "42.2 km · Road · World Marathon Major" },
      desc: {
        el: "Η πιο γρήγορη διαδρομή στον κόσμο — εδώ έχουν πέσει τα περισσότερα παγκόσμια ρεκόρ. Τερματισμός κάτω από την Πύλη του Βρανδεμβούργου.",
        en: "The fastest course in the world — more world records have fallen here than anywhere else. Finish under the Brandenburg Gate.",
      },
      url: { el: "https://www.bmw-berlin-marathon.com/", en: "https://www.bmw-berlin-marathon.com/" },
    },
    {
      id: "copenhagen-half-marathon",
      type: "road", region: "eu", month: 9,
      lat: "55.6761", lng: "12.5683",
      country: { el: "Δανία", en: "Denmark" },
      name: { el: "Ημιμαραθώνιος Κοπεγχάγης", en: "Copenhagen Half Marathon" },
      specs: { el: "21,1 χλμ · Άσφαλτος", en: "21.1 km · Road" },
      desc: {
        el: "Επίπεδη, γρήγορη διαδρομή στο κέντρο της Κοπεγχάγης με τεράστια συμμετοχή — ιδανικός για ατομικό ρεκόρ στον ημιμαραθώνιο.",
        en: "A flat, fast course through central Copenhagen with a huge field — ideal for a half marathon personal best.",
      },
      note: {
        el: "Το 2026 δεν θα διεξαχθεί — η Κοπεγχάγη φιλοξενεί το Παγκόσμιο Πρωτάθλημα Δρόμου της World Athletics. Επιστρέφει τον Σεπτέμβριο του 2027.",
        en: "Not held in 2026 — Copenhagen hosts the World Athletics Road Running Championships instead. Back in September 2027.",
      },
      url: { el: "https://cphhalf.dk/", en: "https://cphhalf.dk/" },
    },
    {
      id: "amsterdam-marathon",
      type: "road", region: "eu", month: 10,
      lat: "52.3676", lng: "4.9041",
      country: { el: "Ολλανδία", en: "Netherlands" },
      name: { el: "Μαραθώνιος Άμστερνταμ", en: "Amsterdam Marathon" },
      specs: { el: "42,2 / 21,1 χλμ · Άσφαλτος", en: "42.2 / 21.1 km · Road" },
      desc: {
        el: "Εκκίνηση και τερματισμός στο Ολυμπιακό Στάδιο του 1928, με διαδρομή δίπλα στον ποταμό Άμστελ — γρήγορος και γραφικός.",
        en: "Start and finish in the 1928 Olympic Stadium, with a course along the Amstel river — fast and scenic.",
      },
      url: { el: "https://www.tcsamsterdammarathon.nl/", en: "https://www.tcsamsterdammarathon.nl/" },
    },
    {
      id: "valencia-marathon",
      type: "road", region: "eu", month: 12,
      lat: "39.4699", lng: "-0.3763",
      country: { el: "Ισπανία", en: "Spain" },
      name: { el: "Μαραθώνιος Βαλένθιας", en: "Valencia Marathon" },
      specs: { el: "42,2 χλμ · Άσφαλτος", en: "42.2 km · Road" },
      desc: {
        el: "Η «πόλη του τρεξίματος»: πανγρήγορη, επίπεδη διαδρομή με εντυπωσιακό τερματισμό πάνω στο νερό, στην Πόλη των Τεχνών και των Επιστημών.",
        en: "The \"city of running\": a lightning-fast, flat course with a spectacular finish over the water at the City of Arts and Sciences.",
      },
      url: { el: "https://www.valenciaciudaddelrunning.com/", en: "https://www.valenciaciudaddelrunning.com/" },
    },
  ],
};
